### ISSUE TITLE
Where is the issue tracker for the JPA 2.2 RI?

### ISSUE THREAD

**Issue by mkarg** [javaee/jpa-spec#154]
@lukasj Lukas, it would be great if you could tell me the link to the JPA 2.2 **RI**'s issue tracker! :-)

**Comment by lukasj** [comment]
to file new bug/rfe/whatever: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=EclipseLink
to query: https://bugs.eclipse.org/bugs/query.cgi?classification=RT&product=EclipseLink

**Comment by mkarg** [comment]
Great, thanks! :-)
