### ISSUE TITLE
move CriteriaQuery#getParameters() to CommonAbstractCriteria

### ISSUE THREAD

**Issue by mkrizmanic** [javaee/jpa-spec#155]
I'd suggest moving the CriteriaQuery#getParameters() method to the CommonAbstractCriteria interface because parameters may be used on the CriteriaUpdate and the CriteriaDelete criterias as well on the common CriteriaQuery.

So I think we should have the same method on the all criteria types to get assigned parameters.

**Comment by lukasj** [comment]
**Closing this as this issue is migrated to** https://github.com/eclipse-ee4j/jpa-api/issues/155
