### ISSUE TITLE
CriteriaBuilder countDistinct() should take multiple expressions

### ISSUE THREAD

**Issue by javaone199** [javaee/jpa-spec#157]
CriteriaBuilder

`Expression<Long> countDistinct(Expression<?> x)`

It should take multiple expressions.

```
Expression<Long> countDistinct(Expression<?> ... expressions)
Expression<Long> countDistinct(List<Expression<?>> expressions)
```

**Comment by lukasj** [comment]
**Closing this as this issue is migrated to** https://github.com/eclipse-ee4j/jpa-api/issues/157
