### ISSUE TITLE
javadoc needs to explain why method generics hides class generics

### ISSUE THREAD

**Issue by javaone199** [javaee/jpa-spec#158]
For example,

Form<Z,X>
```
      <Y> Join<X,Y> join(SingularAttribute<? superX,Y> attribute)
      <X,Y> Join<X,Y>  join(String attributeName);
```

For the 2nd method, why does the method `<X>` hide class `<X>`. It is not clear from javadoc. 
Need to explain why the join's source type is not the target type of the From.

**Comment by lukasj** [comment]
**Closing this as this issue is migrated to** https://github.com/eclipse-ee4j/jpa-api/issues/158
