### ISSUE TITLE
ElementCollection: inconsistency with example

### ISSUE THREAD

**Issue by javaone199** [javaee/jpa-spec#160]
http://docs.oracle.com/javaee/7/api/javax/persistence/ElementCollection.html
Specifies a collection of instances of a basic type or embeddable class.

But example:

http://docs.oracle.com/javaee/7/api/javax/persistence/MapKeyJoinColumn.html
Example 2: map key is entity for ElementCollection.

    @Entity
    public class VideoStore {
       @Id int id;
       String name;
       Address location;
       ...
       @ElementCollection
       @CollectionTable(name="INVENTORY",
                        joinColumns=@JoinColumn(name="STORE"))
       @Column(name="COPIES_IN_STOCK")
       @MapKeyJoinColumn(name="MOVIE", referencedColumnName="ID")
       Map<Movie, Integer> videoInventory;
       ...
     }

     @Entity
     public class Movie {
        @Id long id;
        String title;
        ...
     }

The question is: does ElementCollection allow element type to be Entity? Is it an association in JPA?

**Comment by lukasj** [comment]
**Closing this as this issue is migrated to** https://github.com/eclipse-ee4j/jpa-api/issues/160
