### ISSUE TITLE
NullPointerException in AttributeConverter using CDI @Injection 

### ISSUE THREAD

**Issue by jlmc** [javaee/jpa-spec#161]
I'm trying to use CDI Injection inside an AttributeConverter but without success the value o the reference converter is allways null. 

At this point I'm using Glassfish 5.0 and the AttributeConverter is the following:

```
import javax.inject.Inject;
import javax.persistence.AttributeConverter;
import java.util.Currency;


@javax.persistence.Converter(autoApply = true)
public class CurrencyAttributeConverter implements AttributeConverter<Currency, String> {

    @Inject
    CurrencyConverter converter;

    @Override
    public String convertToDatabaseColumn(Currency attribute) {
        return converter.to(attribute);
    }

    @Override
    public Currency convertToEntityAttribute(String dbData) {
        return this.converter.from(dbData);
    }
}
```

**Comment by andyjefferson** [comment]
Suggest that you report this against the JPA *provider* that you are using (EclipseLink?). 
It is nothing at all to do with the JPA spec, which simply says that a JPA provider should support CDI injection into an `AttributeConverter`.

**Comment by lukasj** [comment]
**Closing this as this issue is migrated to** https://github.com/eclipse-ee4j/jpa-api/issues/161
