### ISSUE TITLE
Support for java.time.Instant

### ISSUE THREAD

**Issue by jacekkruger** [javaee/jpa-spec#163]
Original issue #63 mentioned support for java.time.Instant but it's missing in the final 2.2 spec. I haven't found any reason for omitting it.

I feel it's important for supporting pure UTC data flow as described in the #156. Instant already stores epoch internally so it cleanly maps to a UTC timestamp and it would simplify such use case rather than converting back and forth between different (application, database, user) time zones.

I believe that Instant as a [machine-timeline view](http://blog.joda.org/2009/11/why-jsr-310-isn-joda-time_4941.html) should be the recommended approach for persisting time data over LocalDateTime, OffsetDateTime, ZonedDateTime which are human-timeline views.

Hibernate [supports Instant](http://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#basic-datetime) just fine already and allows changing the database timezone via hibernate.jdbc.time_zone.

**Comment by FelixRiemann** [comment]
Of all the `java.time` types, it is `Instant` that is designed exactly to represent a point in time, so it should be supported. It is also the only type that is suitable for conversion from and to `java.sql.Timestamp`. Of the newly supported types `LocalDate`, `LocalTime`, `LocalDateTime`, `OffsetTime` and `OffsetDateTime`, only the latter actually represents a point in time, but cannot be created from a `Timestamp` alone (the offset is missing).

So if you want to persist a point of time with JPA 2.2, the following options appear to me:
- Use `java.util.Date`
- Use `OffsetDateTime`, but this forces you to choose an offset for all your values. You can use `ZoneOffset.UTC` for all, basically reducing `OffsetDateTime` to an `Instant`. Also, not all popular database systems support persisting an offset along the timestamp value, so you might need to use `@javax.persistence.TemporalTimeZoneColumn`, scattering the value among two columns.
- Use `Instant` and an AttributeConverter, as you already could do before JPA 2.2

Supporting `Instant` sounds preferable to each of these.

**Comment by lukasj** [comment]
**Closing this as this issue is migrated to** https://github.com/eclipse-ee4j/jpa-api/issues/163
