### ISSUE TITLE
Join map key

### ISSUE THREAD

**Issue by javaone199** [javaee/jpa-spec#164]
MapJoin.key() return a Path which can not be a join source. For example,

@Entity
public class Store {
     @ElementCollection(fetch=FetchType.LAZY)
     Map<Merchandise, Integer> inventory;
}

@Entity
public class Merchandise {
     @ManyToOne
      Supplier supplier;
}

CriteriaQuery criteriaQuery = criteriaBuilder.createCriteriaQuery(Store.class);
Root root = criteriaQuery.from(Store.class);
root.join("inventory").key().join("supplier");

The key() return a Path that can not join any association or element collection. Join source must be a From.

1.  need a way to specify the lazy fetch type for map key (Merchandise)? 
2.  need a way to join or join fetch map key (Merchandise)?

**Comment by lukasj** [comment]
**Closing this as this issue is migrated to** https://github.com/eclipse-ee4j/jpa-api/issues/164
