### ISSUE TITLE
static metamodel for multiple persistence units

### ISSUE THREAD

**Issue by javaone199** [javaee/jpa-spec#165]
About generated static metamodel, for example,

@Entity
public class Foo {
    private Long id;
}

@StaticMetamodel(...)
public class Foo_ {

    public static volatile SingleAttribute<Foo, Long> id;

}

If the entity class Foo is in multiple persistence units(each persistence unit has a Metamodel), each Metamodel has a different ManagedType instance for the Foo class. which metamodel does the static attributes (e.g. id in the example) belong? Each attribute has method getDeclaringType() which returns ManagedType instance that is persistence unit specific.

**Comment by lukasj** [comment]
**Closing this as this issue is migrated to** https://github.com/eclipse-ee4j/jpa-api/issues/165
