### ISSUE TITLE
Add a round-function to CriteriaBuilder

### ISSUE THREAD

**Issue by AleksNo** [javaee/jpa-spec#171]
Hello,

sometimes i miss a round function in CriteriaBuilder. Especially when i work with currency values. Many databases support it out of the box. 

The syntax would be:

Expression round(Expression expr, Integer digits)

or:

cb.round(root.get(MyEntity_.value), 2);

Thank you.

Greetings

**Comment by lukasj** [comment]
**Closing this as this issue is migrated to** https://github.com/eclipse-ee4j/jpa-api/issues/171
