### ISSUE TITLE
Adding a where annotation for Entity classes

### ISSUE THREAD

**Issue by dawuzi** [javaee/jpa-spec#172]
Adding the equivalent of a @Where annotation like the one available for hibernate as contained in the link below would be quite useful. It would be awesome too if the annotation accepts the condition in JPQL (Java Persistence Query Language) and not SQL like the hibernate annotation

[https://docs.jboss.org/hibernate/orm/4.1/javadocs/org/hibernate/annotations/Where.html](url)

**Comment by lukasj** [comment]
**Closing this as this issue is migrated to** https://github.com/eclipse-ee4j/jpa-api/issues/172
